"""добавил колонку заверешнности в таблицу задач

Revision ID: 145562a3ac0e
Revises: 
Create Date: 2021-03-27 15:44:41.680116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145562a3ac0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_date')
    # ### end Alembic commands ###
